### PR TITLE
Port to Zephyr v3.5.0 + Fix System Timer

### LINKED ISSUE #112: Zephyr: k_msleep() doesn't work
Hi,

I modified the default `hello_world` sample program to print the Hello World! message in a loop with a delay as follows:

```
diff --git a/samples/hello_world/src/main.c b/samples/hello_world/src/main.c
index 2758d75d3f..a0646c789d 100644
--- a/samples/hello_world/src/main.c
+++ b/samples/hello_world/src/main.c
@@ -5,9 +5,13 @@
  */
 
 #include <stdio.h>
+#include <zephyr/kernel.h>
 
 int main(void)
 {
-       printf("Hello World! %s\n", CONFIG_BOARD);
+       while (1) {
+               printf("Hello World! %s\n", CONFIG_BOARD);
+               k_msleep(1);
+       }
        return 0;
 }
```

However, when I run this, I only get a single Hello World printout (this happens for both Zephyr v3.5.0 and v2.4.0):

```

[markus@571aaf79e9b4 workspace]$ fusesoc run --target=verilator_tb servant --uart_baudrate=57600 --firmware=hello.hex
INFO: Preparing ::serv:1.2.1
INFO: Preparing ::servant:1.2.1
make: Nothing to be done for 'all'.
Loading RAM from /home/markus/workspace/hello.hex
*** Booting Zephyr OS build zephyr-v3.5.0 ***
Hello World! service
^C
Caught ctrl-c

INFO: ****************************
INFO: ****   FuseSoC aborted  ****
INFO: ****************************
```

Can you reproduce this / is this a known limitation of servant/service?

Thanks!
Markus

### PR DESCRIPTION
**Pull request by m42uko**
I did a quick and dirty port to the latest Zephyr OS v3.5.0.

Here's the `hello_world` sample running on servant in verilator:

```
[markus@571aaf79e9b4 workspace]$ fusesoc run --target=verilator_tb servant --uart_baudrate=57600 --firmware=hello.hex
INFO: Preparing ::serv:1.2.1
INFO: Preparing ::servant:1.2.1
make: Nothing to be done for 'all'.
Loading RAM from /home/markus/workspace/hello.hex¨
*** Booting Zephyr OS build zephyr-v3.5.0 ***
Hello World! service
```

To make this cleaner, one should add the registers for the UART (and timer) to the device tree, and read them from there, but I see this as a separate clean-up commit rather than part of this port. If I have the time, I will implement that and open a separate PR for that once this one is merged. Also, we should probably be able to re-use/include some generic code from the RISC-V upstream repo, but again, I think this is a separate PR. Let me know what you think.

EDIT: Also fixes #112 by calling the timer init function using the `SYS_INIT` macro.

### CODE REVIEW

**Comment by m42uko** [comment]
Can confirm that there is a problem here. With the corresponding check removed, the demo runs, but somehow only two of the six philosophers seem to eat:

```
make: Nothing to be done for 'all'.
Loading RAM from /home/markus/workspace/phil.hex
IRQ @0xffeff688 | 0xffeff688
set irq = 0xfff5bdb4
set irq = 0xfff5bdb4
IRQ @0xfff5bdb5 | 0xfff5bdb4
*** Booting Zephyr OS build zephyr-v3.5.0 ***
set irq = 0xfffffc80
set irq = 0xfffffc80
IRQ @0xfffffc81 | 0xfffffc80
Philosopher 0 [C:-2]        STARVING       
Philosopher 0 [C:-2]    HOLDING ONE FORK   
Philosopher 0 [C:-2]   EATING  [  02 ms ] 
set irq = 0x00d609c0
set irq = 0x00d609c0
Philosopher 0 [C:-0]        STARVING       
Philosopher 0 [C:-0]    HOLDING ONE FORK   
Philosopher 2 [P: 0]        STARVING       
Philosopher 2 [P: 0]    HOLDING ONE FORK   
Philosopher 2 [P: 0]        STARVING       
Philosopher 2 [P: 0]    HOLDING ONE FORK   
Philosopher 0 [P: 2]        STARVING       
Philosopher 0 [P: 2]    HOLDING ONE FORK   
Philosopher 0 [P: 2]        STARVING       
IRQ @0x00d609c1 | 0x00d609c0
set irq = 0x00d61f40
set irq = 0x00d61f40
Philosopher 0 [C:-2]    DROPPED ONE FORK   
Philosopher 0 [C:-2]  THINKING [  02 ms ] 
set irq = 0x01408e80
set irq = 0x01408e80
Philosopher 0 [C:-0]   EATING  [  0g ms ] 
set irq = 0x0129cd80
set irq = 0x0129cd80
Philosopher 0 [P: 2]    HOLDING ONE FORK   
IRQ @0x0129cd81 | 0x0129cd80
set irq = 0x01408840
set irq = 0x01408840
Philosopher 0 [C:-0]    DROPPED ONE FORK   
Philosopher 0 [C:-0]  THINKING [  02 ms ] 
Philosopher 2 [P: 0]   EATING  [  08 ms ] 
IRQ @0x01408841 | 0x01408840
set irq = 0x0144a880
set irq = 0x0144a880
Philosopher 0 [C:-2] IRQ @0x0144a881 | 0x0144a880
       STARVING       
set irq = 0x01c01ec0
set irq = 0x01c01ec0
Philosopher 0 [C:-0]        STARVING       
IRQ @0x01c01ec1 | 0x01c01ec0
set irq = 0x01c03440
set irq = 0x01c03440
Philosopher 2 [P: 0]    DROPPED ONE FORK   
Philosopher 2 [P: 0]  THINKING [  08 ms ] 
set irq = 0x01d58800
set irq = 0x01d58800
Philosopher 0 [C:-0]    HOLDING ONE FORK   
IRQ @0x01d58801 | 0x01d58800

Philosopher 0 [C:-0]   EATING  [  0g ms ] 
Philosopher 2 [P: 0]   EATING  [  02 ms ] 
set irq = 0x01ef3700
set irq = 0x01ef3700
Philosopher 2 [P: 0]        STARVING       
IRQ @0x01ef3701 | 0x01ef3700
set irq = 0x02524340
set irq = 0x02524340
Philosopher 0 [C:-0]    DROPPED ONE FORK   
Philosopher 0 [C:-0]  THINKING [  02 ms ] 
IRQ @0x02524341 | 0x02524340
set irq = 0x0258dac0
set irq = 0x0258dac0
Philosopher 2 [P: 0]    DROPPED OIRQ @0x0258dac1 | 0x0258dac0
NE FORK   
Philosopher 2 [P: 0]  THINKING [  02 ms ] 
Philosopher 2 [P: 0]    HOLDING ONE FORK   
Philosopher 2 [P: 0]   EATING  [  08 ms ] 
Philosopher 0 [P: 2]   EATING  [  00 ms ] 
set irq = 0x028e7180
set irq = 0x028e7180
Philosopher 0 [C:-0]        STARVING       
IRQ @0x028e7181 | 0x028e7180
set irq = 0x03100880
set irq = 0x03100880
Philosopher 2 [P: 0]    DROPPED ONE FORK   
Philosopher 2 [P: 0]  THINKING [  08 ms ] 
set irq = 0x02bbc180
set irq = 0x02bbc180
Philosopher 0 [C:-0]    HOLDING ONE FORK   
Philosopher 0 [C:-0]   EATING  [  00 ms ] 
IRQ @0x02bbc181 | 0x02bbc180
set irq = 0x03100880
set irq = 0x03100880
Philosopher 2 [P: 0]        STARVING       
Philosopher 2 [P: 0]    HOLDING ONE FORK   
IRQ @0x03100881 | 0x03100880
set irq = 0x031f95c0
set irq = 0x031f95c0
Philosopher 0 [P: 2]    DROPPED ONE FORK   
Philosopher 0 [P: 2]  THINKING [  02 ms ] 
PIRQ @0x031f95c1 | 0x031f95c0
hilosopher 0 [C:-2]   EATING  [  0g ms ] 
set irq = 0x0361d840
set irq = 0x0361d840
Philosopher 2 [P: 0]        STARVING       
Philosopher 2 [P: 0]    HOLDING ONE FORK   
IRQ @0x0361d841 | 0x0361d840
set irq = 0x036dcec0
set irq = 0x036dcec0
Philosopher 0 [P: 2]        STARVING       
IRQ @0x036dcec1 | 0x036dcec0
set irq = 0x03dcfd40
set irq = 0x03dcfd40
Philosopher 0 [C:-0]    DROPPED ONE FORK   
Philosopher 0 [C:-0]  THINKING [  02 ms ] 
Philosopher 2 [P: 0]   EATING  [  08 ms ] 
IRQ @0x03dcfd41 | 0x03dcfd40
set irq = 0x03ea5800
set irq = 0x03ea5800
Philosopher 0 [C:-2]    DROPPED ONE FORK   
Philosopher 0 [P: 2]  THINKING [ IRQ @0x03ea5801 | 0x03ea5800
 0g ms ] 
Philosopher 0 [C:-2]    HOLDING ONE FORK   
Philosopher 0 [C:-2]   EATING  [  02 ms ] 
Philosopher 0 [P: 2]    HOLDING ONE FORK   
```

Like you said, hold off merging this until we fix this and the timer overflow issue.

**Comment by olofk** [comment]
I think we have several problems. I just realigned serv_timer to the upstream riscv_machine_timer from zephyr 3.5.0 and there were quite a few changes. But I also believe there are other problems in the RTL and/or the board support code. One thing I have knowingly cheated with in the RTL is to not make the MPIE bit in the MSTATUS register accessible from software. Perhaps this worked before, but not any more. I also remember that a lot of the files in the SERV-specific zephyr/soc directory had to be copied there because of some limitation in Zephyr when using an external soc dir. Maybe these files need to be refreshed (or best of all removed!) now.

**Comment by m42uko** [comment]
Oof, you're probably right. I just noticed that not even printf is working properly. It prints something like "0g0" when I try to use %d or %x. I feel like most of our issues at this point are not interrupt related even, but I have no idea how to get started troubleshooting this right now.

**Comment by m42uko** [comment]
>  I just noticed that not even printf is working properly.
Okay that problems seems to be because I still have MUL instructions in picolibc code. As far as I know, that library is precompiled and ships with their toolchain (I'm on v0.16.4).

**Comment by m42uko** [comment]
Yup, that fixes this issue. So that's most likely an upstream bug.

**Comment by m42uko** [comment]
Oh, neat, that also improves the philosophers situation. It's still unhappy about the assertion, but once it is removed (in `kernel/include/kswap.h`), the test seems to run. OK, I'll take a break now and verify which other issues this resolves (maybe this also makes my 10-minute-timer problem go away.)

**Comment by m42uko** [comment]
Yup, this seems to also fix the 10-minute lockup (has been running for half an hour now with multiple overflows). So I'll have to apologize to @alinja, PR #109 seems to do what it promises, the overflow works. (Again, I didn't check that there aren't any weird timing artifacts, but the basic functionality looks good.) Log, 1 s sleep: [hello_world_with_timer.log](https://github.com/olofk/serv/files/13617040/hello_world_with_timer.log)

**Comment by m42uko** [comment]
I agree, this should be good to merge.

I think it's a good idea to open an Issue regarding the assertion just to keep track of it, and the (possibly upstream) compiler issue I'll try to chase down later in the week.

**Comment by olofk** [comment]
I filed https://github.com/olofk/serv/issues/113 now to keep track of that issue. Thanks for working on this. Picked and pushed!

**Pull request merged**
