### PR TITLE
chameleon96 board support added

### PR DESCRIPTION
**Pull request by somhi**

### CODE REVIEW

**Comment by olofk** [comment]
Good looks fine. Thank you for your work. I see there are two lines in the readme file that got some extra whitespace.  If you could just remove  that I am happy to accept this

**Comment by somhi** [comment]
ok removes spaces :)

**Comment by olofk** [comment]
Great! Thank you for your contribution.

BTW, did you try if setting `board_device_index : 2` worked?

**Comment by somhi** [comment]
yes it worked!!  I've updated blinky, serv & corescore with that. Do you want me to PR those ?

**Comment by olofk** [comment]
That would be great!

**Pull request merged**
