### PR TITLE
Add Saanlima pipistrello spartan6 LX45 with note for WA due to ISE bugs

### PR DESCRIPTION
**Pull request by trabucayre**
Work (blink and uart) with some modifications (see note) to avoid ISE bugs

### CODE REVIEW

**Comment by olofk** [comment]
Great to know that it works with ISE (with the workarounds).

For the $display issue I think we can just add an `` `ifndef ISE`` around it and set this define for the relevant targets. For the localparam problems, could you check it it's enough to just define them as `parameter` instead of `localparam` instead of hardcoding a value?

**Comment by trabucayre** [comment]
It's true.
Updated the PR

**Comment by olofk** [comment]
I pulled in your changes and made a similar target for my LX9 microboard, and amazingly, it works :)

Could you just submit the ifndef ISE and changes from localparam to parameter as a separate commit first. That makes it clearer what's going on. I'm happy to make the changes here instead if you prefer that.

**Comment by trabucayre** [comment]
I think the best way is:
1/ I close this PR.
2/ I send a PR for ISE compatibility
3/ I send pipistrello support.
Thus, It is more clear in git log and in pull request too.
As you want

**Comment by olofk** [comment]
Perfect!

**Pull request closed without merging**
